using Microsoft.EntityFrameworkCore;
using TradesApi.Data.EntityFramework.Entities;

namespace TradesApi.Data.EntityFramework
{
    public class TradesApiContext : DbContext
    {
        private bool _configured = false;

        public TradesApiContext() : base()
        {
        }

        public TradesApiContext(DbContextOptions<TradesApiContext> options) : base(options)
        {
            _configured = true;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLazyLoadingProxies();
            if (!_configured)
            {
                optionsBuilder.UseSqlite("Data Source=../TradesApi.db");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CurrencyEntity>().HasData(new CurrencyEntity[] {
                new CurrencyEntity() { Id = 1, Code = "AED" },
                new CurrencyEntity() { Id = 2, Code = "AFN" },
                new CurrencyEntity() { Id = 3, Code = "ALL" },
                new CurrencyEntity() { Id = 4, Code = "AMD" },
                new CurrencyEntity() { Id = 5, Code = "ANG" },
                new CurrencyEntity() { Id = 6, Code = "AOA" },
                new CurrencyEntity() { Id = 7, Code = "ARS" },
                new CurrencyEntity() { Id = 8, Code = "AUD" },
                new CurrencyEntity() { Id = 9, Code = "AWG" },
                new CurrencyEntity() { Id = 10, Code = "AZN" },
                new CurrencyEntity() { Id = 11, Code = "BAM" },
                new CurrencyEntity() { Id = 12, Code = "BBD" },
                new CurrencyEntity() { Id = 13, Code = "BDT" },
                new CurrencyEntity() { Id = 14, Code = "BGN" },
                new CurrencyEntity() { Id = 15, Code = "BHD" },
                new CurrencyEntity() { Id = 16, Code = "BIF" },
                new CurrencyEntity() { Id = 17, Code = "BMD" },
                new CurrencyEntity() { Id = 18, Code = "BND" },
                new CurrencyEntity() { Id = 19, Code = "BOB" },
                new CurrencyEntity() { Id = 20, Code = "BRL" },
                new CurrencyEntity() { Id = 21, Code = "BSD" },
                new CurrencyEntity() { Id = 22, Code = "BTC" },
                new CurrencyEntity() { Id = 23, Code = "BTN" },
                new CurrencyEntity() { Id = 24, Code = "BWP" },
                new CurrencyEntity() { Id = 25, Code = "BYN" },
                new CurrencyEntity() { Id = 26, Code = "BZD" },
                new CurrencyEntity() { Id = 27, Code = "CAD" },
                new CurrencyEntity() { Id = 28, Code = "CDF" },
                new CurrencyEntity() { Id = 29, Code = "CHF" },
                new CurrencyEntity() { Id = 30, Code = "CLF" },
                new CurrencyEntity() { Id = 31, Code = "CLP" },
                new CurrencyEntity() { Id = 32, Code = "CNH" },
                new CurrencyEntity() { Id = 33, Code = "CNY" },
                new CurrencyEntity() { Id = 34, Code = "COP" },
                new CurrencyEntity() { Id = 35, Code = "CRC" },
                new CurrencyEntity() { Id = 36, Code = "CUC" },
                new CurrencyEntity() { Id = 37, Code = "CUP" },
                new CurrencyEntity() { Id = 38, Code = "CVE" },
                new CurrencyEntity() { Id = 39, Code = "CZK" },
                new CurrencyEntity() { Id = 40, Code = "DJF" },
                new CurrencyEntity() { Id = 41, Code = "DKK" },
                new CurrencyEntity() { Id = 42, Code = "DOP" },
                new CurrencyEntity() { Id = 43, Code = "DZD" },
                new CurrencyEntity() { Id = 44, Code = "EGP" },
                new CurrencyEntity() { Id = 45, Code = "ERN" },
                new CurrencyEntity() { Id = 46, Code = "ETB" },
                new CurrencyEntity() { Id = 47, Code = "EUR" },
                new CurrencyEntity() { Id = 48, Code = "FJD" },
                new CurrencyEntity() { Id = 49, Code = "FKP" },
                new CurrencyEntity() { Id = 50, Code = "GBP" },
                new CurrencyEntity() { Id = 51, Code = "GEL" },
                new CurrencyEntity() { Id = 52, Code = "GGP" },
                new CurrencyEntity() { Id = 53, Code = "GHS" },
                new CurrencyEntity() { Id = 54, Code = "GIP" },
                new CurrencyEntity() { Id = 55, Code = "GMD" },
                new CurrencyEntity() { Id = 56, Code = "GNF" },
                new CurrencyEntity() { Id = 57, Code = "GTQ" },
                new CurrencyEntity() { Id = 58, Code = "GYD" },
                new CurrencyEntity() { Id = 59, Code = "HKD" },
                new CurrencyEntity() { Id = 60, Code = "HNL" },
                new CurrencyEntity() { Id = 61, Code = "HRK" },
                new CurrencyEntity() { Id = 62, Code = "HTG" },
                new CurrencyEntity() { Id = 63, Code = "HUF" },
                new CurrencyEntity() { Id = 64, Code = "IDR" },
                new CurrencyEntity() { Id = 65, Code = "ILS" },
                new CurrencyEntity() { Id = 66, Code = "IMP" },
                new CurrencyEntity() { Id = 67, Code = "INR" },
                new CurrencyEntity() { Id = 68, Code = "IQD" },
                new CurrencyEntity() { Id = 69, Code = "IRR" },
                new CurrencyEntity() { Id = 70, Code = "ISK" },
                new CurrencyEntity() { Id = 71, Code = "JEP" },
                new CurrencyEntity() { Id = 72, Code = "JMD" },
                new CurrencyEntity() { Id = 73, Code = "JOD" },
                new CurrencyEntity() { Id = 74, Code = "JPY" },
                new CurrencyEntity() { Id = 75, Code = "KES" },
                new CurrencyEntity() { Id = 76, Code = "KGS" },
                new CurrencyEntity() { Id = 77, Code = "KHR" },
                new CurrencyEntity() { Id = 78, Code = "KMF" },
                new CurrencyEntity() { Id = 79, Code = "KPW" },
                new CurrencyEntity() { Id = 80, Code = "KRW" },
                new CurrencyEntity() { Id = 81, Code = "KWD" },
                new CurrencyEntity() { Id = 82, Code = "KYD" },
                new CurrencyEntity() { Id = 83, Code = "KZT" },
                new CurrencyEntity() { Id = 84, Code = "LAK" },
                new CurrencyEntity() { Id = 85, Code = "LBP" },
                new CurrencyEntity() { Id = 86, Code = "LKR" },
                new CurrencyEntity() { Id = 87, Code = "LRD" },
                new CurrencyEntity() { Id = 88, Code = "LSL" },
                new CurrencyEntity() { Id = 89, Code = "LYD" },
                new CurrencyEntity() { Id = 90, Code = "MAD" },
                new CurrencyEntity() { Id = 91, Code = "MDL" },
                new CurrencyEntity() { Id = 92, Code = "MGA" },
                new CurrencyEntity() { Id = 93, Code = "MKD" },
                new CurrencyEntity() { Id = 94, Code = "MMK" },
                new CurrencyEntity() { Id = 95, Code = "MNT" },
                new CurrencyEntity() { Id = 96, Code = "MOP" },
                new CurrencyEntity() { Id = 97, Code = "MRO" },
                new CurrencyEntity() { Id = 98, Code = "MRU" },
                new CurrencyEntity() { Id = 99, Code = "MUR" },
                new CurrencyEntity() { Id = 100, Code = "MVR" },
                new CurrencyEntity() { Id = 101, Code = "MWK" },
                new CurrencyEntity() { Id = 102, Code = "MXN" },
                new CurrencyEntity() { Id = 103, Code = "MYR" },
                new CurrencyEntity() { Id = 104, Code = "MZN" },
                new CurrencyEntity() { Id = 105, Code = "NAD" },
                new CurrencyEntity() { Id = 106, Code = "NGN" },
                new CurrencyEntity() { Id = 107, Code = "NIO" },
                new CurrencyEntity() { Id = 108, Code = "NOK" },
                new CurrencyEntity() { Id = 109, Code = "NPR" },
                new CurrencyEntity() { Id = 110, Code = "NZD" },
                new CurrencyEntity() { Id = 111, Code = "OMR" },
                new CurrencyEntity() { Id = 112, Code = "PAB" },
                new CurrencyEntity() { Id = 113, Code = "PEN" },
                new CurrencyEntity() { Id = 114, Code = "PGK" },
                new CurrencyEntity() { Id = 115, Code = "PHP" },
                new CurrencyEntity() { Id = 116, Code = "PKR" },
                new CurrencyEntity() { Id = 117, Code = "PLN" },
                new CurrencyEntity() { Id = 118, Code = "PYG" },
                new CurrencyEntity() { Id = 119, Code = "QAR" },
                new CurrencyEntity() { Id = 120, Code = "RON" },
                new CurrencyEntity() { Id = 121, Code = "RSD" },
                new CurrencyEntity() { Id = 122, Code = "RUB" },
                new CurrencyEntity() { Id = 123, Code = "RWF" },
                new CurrencyEntity() { Id = 124, Code = "SAR" },
                new CurrencyEntity() { Id = 125, Code = "SBD" },
                new CurrencyEntity() { Id = 126, Code = "SCR" },
                new CurrencyEntity() { Id = 127, Code = "SDG" },
                new CurrencyEntity() { Id = 128, Code = "SEK" },
                new CurrencyEntity() { Id = 129, Code = "SGD" },
                new CurrencyEntity() { Id = 130, Code = "SHP" },
                new CurrencyEntity() { Id = 131, Code = "SLL" },
                new CurrencyEntity() { Id = 132, Code = "SOS" },
                new CurrencyEntity() { Id = 133, Code = "SRD" },
                new CurrencyEntity() { Id = 134, Code = "SSP" },
                new CurrencyEntity() { Id = 135, Code = "STD" },
                new CurrencyEntity() { Id = 136, Code = "STN" },
                new CurrencyEntity() { Id = 137, Code = "SVC" },
                new CurrencyEntity() { Id = 138, Code = "SYP" },
                new CurrencyEntity() { Id = 139, Code = "SZL" },
                new CurrencyEntity() { Id = 140, Code = "THB" },
                new CurrencyEntity() { Id = 141, Code = "TJS" },
                new CurrencyEntity() { Id = 142, Code = "TMT" },
                new CurrencyEntity() { Id = 143, Code = "TND" },
                new CurrencyEntity() { Id = 144, Code = "TOP" },
                new CurrencyEntity() { Id = 145, Code = "TRY" },
                new CurrencyEntity() { Id = 146, Code = "TTD" },
                new CurrencyEntity() { Id = 147, Code = "TWD" },
                new CurrencyEntity() { Id = 148, Code = "TZS" },
                new CurrencyEntity() { Id = 149, Code = "UAH" },
                new CurrencyEntity() { Id = 150, Code = "UGX" },
                new CurrencyEntity() { Id = 151, Code = "USD" },
                new CurrencyEntity() { Id = 152, Code = "UYU" },
                new CurrencyEntity() { Id = 153, Code = "UZS" },
                new CurrencyEntity() { Id = 154, Code = "VEF" },
                new CurrencyEntity() { Id = 155, Code = "VES" },
                new CurrencyEntity() { Id = 156, Code = "VND" },
                new CurrencyEntity() { Id = 157, Code = "VUV" },
                new CurrencyEntity() { Id = 158, Code = "WST" },
                new CurrencyEntity() { Id = 159, Code = "XAF" },
                new CurrencyEntity() { Id = 160, Code = "XAG" },
                new CurrencyEntity() { Id = 161, Code = "XAU" },
                new CurrencyEntity() { Id = 162, Code = "XCD" },
                new CurrencyEntity() { Id = 163, Code = "XDR" },
                new CurrencyEntity() { Id = 164, Code = "XOF" },
                new CurrencyEntity() { Id = 165, Code = "XPD" },
                new CurrencyEntity() { Id = 166, Code = "XPF" },
                new CurrencyEntity() { Id = 167, Code = "XPT" },
                new CurrencyEntity() { Id = 168, Code = "YER" },
                new CurrencyEntity() { Id = 169, Code = "ZAR" },
                new CurrencyEntity() { Id = 170, Code = "ZMW" },
                new CurrencyEntity() { Id = 171, Code = "ZWL" },
            });
        }

        public DbSet<CurrencyEntity> Currencies { get; set; }

        public DbSet<TradeEntity> Trades { get; set; }
    }
}
