// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradesApi.Data.EntityFramework;

namespace TradesApi.Data.EntityFramework.Migrations
{
    [DbContext(typeof(TradesApiContext))]
    partial class TradesApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("TradesApi.Data.EntityFramework.Entities.CurrencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("TradesApi.Data.EntityFramework.Entities.TradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AskCurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidCurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BoughtByClientAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BoughtByUsAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoldAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AskCurrencyId");

                    b.HasIndex("BidCurrencyId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("TradesApi.Data.EntityFramework.Entities.TradeEntity", b =>
                {
                    b.HasOne("TradesApi.Data.EntityFramework.Entities.CurrencyEntity", "AskCurrency")
                        .WithMany()
                        .HasForeignKey("AskCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradesApi.Data.EntityFramework.Entities.CurrencyEntity", "BidCurrency")
                        .WithMany()
                        .HasForeignKey("BidCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
